bsp-kpda-1892vm14-salute-el24d1: ethernet driver for Salute board added

diff --git a/src/hardware/startup/boards/1892vm14/salute-el24d1/build b/src/hardware/startup/boards/1892vm14/salute-el24d1/build
--- a/src/hardware/startup/boards/1892vm14/salute-el24d1/build
+++ b/src/hardware/startup/boards/1892vm14/salute-el24d1/build
@@ -7,7 +7,7 @@
 [image=0x40100000]
 [virtual=armle-v7,raw +compress] .bootstrap = {
 	# Watchdog can be enabled using '-W' startup option
-	startup-salute-el24d1 -vvv
+	startup-salute-el24d1 -vvv -Nel24d1
 	# '-ae' startup option allows for unaligned memory accesses
 	PATH=/proc/boot procnto-smp -ae 
 }
@@ -27,21 +27,23 @@
 
     # Start some common servers
     pipe &
-    
+
+#    network_setup -e 172.16.10.75 -t -i -q -d
+
     devc-pty
     waitfor /dev/ptyp0 4
 
     # Start the main shell
     SYSNAME=nto
     TERM=qansi
-    HOME=/
+    HOME=/tmp
     PATH=:/bin:/usr/bin:/sbin:/usr/sbin:/proc/boot
     LD_LIBRARY_PATH=:/lib:/usr/lib:/lib/dll:/proc/boot
     
     waitfor /dev/ser1 5
     reopen /dev/ser1
     
-    [+session] ksh &
+    [+session] ksh -l &
 }
 
 # Redirect console messages
@@ -53,8 +55,21 @@
 
 # Shared libraries
 libc.so
+libz.so.2
 libm.so.2
 libc.so.3
+libstdc++.so.6
+
+#######################################################################
+## Networking libs and drivers
+#######################################################################
+#devnp-1892vm14-gemac.so
+#libsocket.so
+#libssl.so
+#libcrypto.so
+#libnbutil.so
+#lsm-qnet.so
+## lsm-qnet-ksz.so
 
 
 ###########################################################################
@@ -77,12 +92,6 @@ libc.so.3
 #fs-qnx4.so
 #fs-dos.so
 
-###########################################################################
-## uncomment for NETWORK driver
-###########################################################################
-#libsocket.so
-#[perms=+r,+x] devnp-arasan-gemac.so
-
 # Executables
 [data=c dperms=0755]
 
@@ -91,10 +100,23 @@ libc.so.3
 ###########################################################################
 devc-ser8250
 
-###########################################################################
-## uncomment for NETWORK driver
-###########################################################################
+#######################################################################
+## Networking stuff
+#######################################################################
 #io-pkt-v4-hc
+#random
+#ping
+#route
+#ftp
+#telnet
+#inetd
+#telnetd
+#ftpd
+#ifconfig
+#netstat
+#nicinfo
+#fs-nfs3
+#login
 
 ###########################################################################
 ## uncomment for USB HOST driver
@@ -143,20 +165,159 @@ chmod
 ln
 rm
 mv
-sleep
 random
 dd
 top
 touch
 stty
-date
 cksum
+
+echo
+mkdir
+df
+hostname
+waitfor
+ntpd
 
 #hidview
 
-#ifconfig
-#nicinfo
-#ping
+#######################################################################
+## Debug stuff
+#######################################################################
+qconn
+pdebug
+
+[type=link] /bin/login=/proc/boot/login
+
+/etc/profile = {
+export TZ=MSK-03
+}
+
+/etc/ntp.conf = {
+server 172.16.10.72
+driftfile /etc/ntp/ntp.drift
+}
+
+/etc/ftpusers = {
+* allow
+}
+/etc/inetd.conf = {
+ftp        stream tcp nowait root  /proc/boot/ftpd           in.ftpd -l
+telnet     stream tcp nowait root  /proc/boot/telnetd        in.telnetd
+}
+
+/etc/services = ${QNX_TARGET}/etc/services
+
+/etc/passwd = {
+root:x:0:0:Superuser:/tmp:/bin/sh
+}
+
+/etc/shadow = {
+root:365095DDA5BA51F86587F9E4E9DA5084E149C01940DC6F56F8342DBCBBA3DF88B20E80375E8EF5A63F66159F6100909F537023C2B70930D6A6EF2A3423B9BECAFM:1432602763:0:0
+}
+
+###########################################################################
+## SCRIPTS
+###########################################################################
+[perms=u+x uid=0 gid=0] start_ntpd = {
+#!/proc/boot/ksh
+	ntpd -gq >/dev/null 2>&1
+	ntpd -c /etc/ntp.conf
+}
+
+[perms=u+x uid=0 gid=0] network_setup = {
+#!/proc/boot/ksh
+
+random >/dev/null 2>&1 &
+USE_QNET=0
+USE_QCONN=0
+USE_INETD=0
+USE_NFS=0
+USE_NTPD=0
+while getopts e:tqdin  opt $*; do
+	case $opt in
+		e)
+			IP_ADDR_ETH="$OPTARG"
+			;;
+		t)
+			USE_NTPD=1
+			;;
+		q)
+			USE_QNET=1
+			;;
+		d)
+			USE_QCONN=1
+			;;
+		i)
+			USE_INETD=1
+			;;
+		n)
+			USE_NFS=1
+			;;
+	esac
+done
+
+if [ -e "/dev/socket" ]; then
+	echo "Net already up"
+	exit 1
+fi
+
+echo -n "Starting ethernet driver..."
+waitfor /dev/random 5
+waitfor /dev/slog 5
+io-pkt-v4-hc -ptcpip forward,stacksize=8192 > /tmp/net.log 2>&1
+# io-pkt-v4 -dcprio64 mac=005056c00018 -ptcpip forward -pqnet
+# io-pkt-v4 -dcprio64 -ptcpip forward -pqnet
+# io-pkt-v4 -d1890vm8-gbe receive=2048,transmit=2048 -ptcpip -pqnet
+waitfor /dev/bpf0 5 >> /tmp/net.log 2>&1
+waitfor /dev/socket 5 >> /tmp/net.log 2>&1
+
+if [ -e "/dev/socket" ]; then
+# 	mount -T io-pkt -o transmit=128,tx_reap=16 devnp-1892vm14-gemac.so >> /tmp/net.log 2>&1
+	mount -T io-pkt -o verbose,mac=e25eff95ac76,transmit=128 devnp-1892vm14-gemac.so >> /tmp/net.log 2>&1
+	ret=$?
+	if [ $ret -eq 0 ]; then
+		echo " OK"
+	else
+		echo " FAIL"
+		exit 1
+	fi
+	if [ -n "$IP_ADDR_ETH" ]; then
+		echo "Configure ethernet interface to address $IP_ADDR_ETH"
+		ifconfig en0 "$IP_ADDR_ETH" up
+	fi
+	if [ $USE_QNET ]; then
+		echo "Starting qnet..."
+# 		mount -Tio-pkt -oprotected=1 lsm-qnet-ksz.so
+		mount -Tio-pkt lsm-qnet.so
+	fi
+	if [ $USE_QCONN ]; then
+		echo "Starting qconn..."
+		qconn qconn_prio=250 &
+	fi
+	if [ $USE_INETD ]; then
+		echo "Starting inetd..."
+		inetd &
+	fi
+	if [ $USE_NTPD ]; then
+		echo "Setup time..."
+		echo "127.0.0.1 localhost" > /tmp/hosts
+		ln -sP /tmp/hosts /etc/hosts
+		start_ntpd &
+	fi
+	if [ $USE_NFS -eq 1 ]; then
+		echo "Starting nfs..."
+# 		fs-nfs3 192.168.1.80:/armle-v7 /nfs &
+		waitfor /nfs 15
+		for path in /etc /var /root/ /usr/lib /usr/libexec; do
+			ln -sP /nfs$path $path
+		done
+		`which sshd`
+	fi
+else
+	echo " FAIL"
+fi
+}
 
 ###########################################################################
 ## END OF BUILD SCRIPT
